import turtle as t
bikash = t.Turtle()
bikash.color('red')
t.color("red","yellow")
t.begin_fill()
bikash.shape("turtle")
for i in range(2):
    bikash.forward(100)
    bikash.left(90)
bikash.right(150)
bikash.forward(60)
bikash.left(90)
bikash.forward(50)
bikash.left(90)
bikash.forward(40)
bikash.right(100)
bikash.forward(20)
bikash.left(90)
bikash.forward(20)
bikash.right(60)
bikash.forward(20)
bikash.left(90)
bikash.forward(20)
bikash.right(100)
bikash.forward(40)
bikash.left(90)
bikash.forward(50)
bikash.left(90)
bikash.forward(50)
bikash.right(50)
bikash.forward(130)
bikash.left(120)
bikash.forward(122)
bikash.left(70)
bikash.forward(70)
bikash.left(90)
bikash.forward(20)
bikash.right(90)

t.end_fill()
t.done()
